### ISSUE TITLE
on-drop-success not fired in IE

### ISSUE THREAD

**Issue by timjnh** [angular-dragdrop/angular-dragdrop#109] opened 2014-12-10 17:54 UTC
It seems that the onDropSuccess handler is not being fired in IE (at least 11).  It appears it's because dragend always receives the dropEffect as 'none' when effectAllowed is set to copyMove.  If you change effectAllowed to either copy or move, rather than the combined term, things work fine.  

Was able to reproduce pretty easily using test.html from the example.  You'll notice that you can't drop any items into the other lists.

What about requiring shift to be pressed at the start of the copy/move rather than allowing it during the drag?

**Comment by Schweigi** [comment] 2015-03-13 19:35
I tested with IE11 too and the problem is that there is an exception when accessing `dataTransfer.setData`. In my opinion this issue is a duplicate of #96.

**Closed** 2015-03-14 09:20 UTC
